# Generated by Django 5.2.4 on 2025-07-07 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('birth_year', models.SmallIntegerField(blank=True, null=True)),
                ('death_year', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'books_author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('gutenberg_id', models.IntegerField(unique=True)),
                ('media_type', models.CharField(max_length=16)),
                ('download_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'books_book',
            },
        ),
        migrations.CreateModel(
            name='Bookshelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'books_bookshelf',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'books_language',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'books_subject',
            },
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_books', to='books_app.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='books_app.book')),
            ],
            options={
                'db_table': 'books_book_authors',
                'unique_together': {('book', 'author')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', through='books_app.BookAuthor', to='books_app.author'),
        ),
        migrations.CreateModel(
            name='BookBookshelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_bookshelves', to='books_app.book')),
                ('bookshelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookshelf_books', to='books_app.bookshelf')),
            ],
            options={
                'db_table': 'books_book_bookshelves',
                'unique_together': {('book', 'bookshelf')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='bookshelves',
            field=models.ManyToManyField(related_name='books', through='books_app.BookBookshelf', to='books_app.bookshelf'),
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mime_type', models.CharField(max_length=32)),
                ('url', models.URLField(max_length=256)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formats', to='books_app.book')),
            ],
            options={
                'db_table': 'books_format',
            },
        ),
        migrations.CreateModel(
            name='BookLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_languages', to='books_app.book')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language_books', to='books_app.language')),
            ],
            options={
                'db_table': 'books_book_languages',
                'unique_together': {('book', 'language')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='languages',
            field=models.ManyToManyField(related_name='books', through='books_app.BookLanguage', to='books_app.language'),
        ),
        migrations.CreateModel(
            name='BookSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_subjects', to='books_app.book')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_books', to='books_app.subject')),
            ],
            options={
                'db_table': 'books_book_subjects',
                'unique_together': {('book', 'subject')},
            },
        ),
        migrations.AddField(
            model_name='book',
            name='subjects',
            field=models.ManyToManyField(related_name='books', through='books_app.BookSubject', to='books_app.subject'),
        ),
    ]
